openapi: 3.0.0
info:
  title: Artifan API - Authentication
  version: 1.1.0
  description: 'API de autenticación para usuarios (clientes o artistas)'
servers:
  - url: https://artifan.victorcastro.io
    description: API principal
paths:
  /api/login:
    parameters: []
    post:
      summary: Login
      parameters:
        - name: Authorization
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Usuario autenticado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "2|ODCQAyBU5VWPMqntEE5qTJW91JEUnk5KHzAnOIGD2e3b0fc0"
        '422':
          description: Error de validación
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: El número de celular es obligatorio
                  error:
                    type: string
                    example: ValidationException
                  errors:
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        type: string
                    example:
                      mobile_number:
                        - El número de celular es obligatorio
        
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                mobile_number:
                  type: string
                  example: "928218253"
                mobile_prefix:
                  type: string
                  example: "+51"
                password:
                  type: string
                  example: "secret"
  /api/register:
    parameters: []
    post:
      summary: Register
      parameters: []
      responses:
        '200':
          description: Registro exitoso, OTP enviado
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: 4|2d9TAADaSDTAKnkhXQsT5YG4Ssb7Ua2rmwZVxirW60c83f31
                  message:
                    type: string
                    example: OTP enviado exitosamente al número 92****253
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstname:
                  type: string
                city:
                  type: string
                country_id:
                  type: string
                mobile_number:
                  type: string
                  format: utc-millisec
                mobile_prefix:
                  type: string
                  format: utc-millisec
                password:
                  type: string
  /api/me:
    parameters: []
    get:
      summary: Me
      parameters:
        - name: Authorization
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Datos del usuario autenticado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 6
                  firstname:
                    type: string
                    example: Victor
                  lastname:
                    type: string
                    nullable: true
                    example: null
                  docnum:
                    type: string
                    nullable: true
                    example: null
                  doctype:
                    type: string
                    nullable: true
                    example: null
                  mobileE164:
                    type: string
                    example: "+51928218253"
                  mobileE164_verified_at:
                    type: string
                    format: date-time
                    nullable: true
                    example: null
                  mobile_number:
                    type: string
                    example: "928218253"
                  mobile_prefix:
                    type: string
                    example: "+51"
                  city:
                    type: string
                    example: "Lima"
                  country_id:
                    type: string
                    example: "PER"
                  created_at:
                    type: string
                    format: date-time
                    example: "2025-07-31T13:55:18+00:00"
  /api/logout:
    parameters: []
    post:
      summary: Logout
      parameters:
        - name: Authorization
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Sesión cerrada correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Sesión cerrada correctamente"
      requestBody:
        content:
          application/json:
            schema:
              type: object
  /api/mobile/otp/resend:
    parameters: []
    post:
      summary: OTP Re-send
      parameters: []
      responses:
        '200':
          description: OTP enviado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "OTP enviado exitosamente al número 928****253"
        '422':
          description: Error al enviar el código de OTP
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Hubo un error al enviar el código de OTP
      requestBody:
        content:
          application/json:
            schema:
              type: object
  /api/mobile/otp/verify:
    parameters: []
    post:
      summary: OTP Validate
      parameters: []
      responses:
        '200':
          description: Número verificado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Número verificado correctamente
        '400':
          description: Código inválido o expirado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Código inválido o expirado
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                otp:
                  type: string
                  format: color
  /api/password/forgot:
    parameters: []
    post:
      summary: Password Forgot
      parameters: []
      responses:
        '200':
          description: Código de recuperación enviado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Se ha enviado un código de recuperación por SMS
        '422':
          description: Error al enviar el código de recuperación
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Error al enviar el código de recuperación
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                mobile_prefix:
                  type: string
                  example: "+51"
                mobile_number:
                  type: string
                  example: "928218253"
  /api/password/reset:
    parameters: []
    post:
      summary: Password Reset
      parameters:
        - name: Authorization
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Contraseña restablecida correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: La contraseña se ha restablecido correctamente
        '400':
          description: Código inválido o expirado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: El código ingresado es inválido o ha expirado
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                mobile_prefix:
                  type: string
                  format: utc-millisec
                mobile_number:
                  type: string
                  format: utc-millisec
                otp:
                  type: string
                  format: color
                new_password:
                  type: string
